{% set name = "npctypes" %}
{% set version = "0.0.4" %}
{% set sha256 = "4832bfce8dbc35298c8bea7d1533c9f500691a51719fb10bb2ffce59123d5e50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  source_files:
    - tests

  imports:
    - npctypes

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/jakirkham/npctypes
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python utility functions for slices.
  doc_url: https://npctypes.readthedocs.io/
  dev_url: https://github.com/jakirkham/npctypes

extra:
  recipe-maintainers:
    - jakirkham
