{% set name = "npctypes" %}
{% set version = "0.0.3" %}
{% set sha256 = "c479357f73817142468d0e9f0c9f17ba58a6e16b6960f53f0bbd6a98038e513e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  source_files:
    - tests

  imports:
    - npctypes

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/jakirkham/npctypes
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python utility functions for slices.
  doc_url: https://npctypes.readthedocs.io/
  dev_url: https://github.com/jakirkham/npctypes

extra:
  recipe-maintainers:
    - jakirkham
