# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HgeExTsRD5YIIi/coz2cFi0RyScVTa1H+cRerJ1jSQlMNwqHUIUmTUgg6Vo1/tb24AEPmykW8t0okgkmxroXrr239XZc3KLoZRKSMU3zYyuZbICJ1Pcc1Vj5WavujLvvS3je/JX47We6c6etg7iVfzWjkggl3DnD8GIPaS9J5PSmf/d09FuBNYmbO4teq3c/15+LMNMcGRNTaXU6XR1H3irv9v+IF+o+p3cPNGjLjKal1A8PMVLPYb8W93SKU4Qbg5SpNwfNTMAlq7+oZNY2SfynVTVT7+zcFjpGh/UTBUpjyswYAad+iJN5T2a1UBqdJTYNWDBc9erlIT5zdPLTMFxMz6v5e0uGvIF9dFy8QYIIrFpEeRuKGVW7pq/xf8qle69QJ9D/tVZiQn5VSx+gmJ6C4j6pFdV72vKDlcsuTxv+9GNUGB/AOzi81JlXVrZsxSwLwUjnuKtPRkOYriqHb8EJE8ivAPDolDVK60fK1u/pcqun+jDbatfDQIwmvB6eJ1TR/NhDhdoRj/18A37/x/vDez9pC/9ykjEXmP1hRq3wpLO1Je+oDCkTX9f6vHqjlgup+wYTcsZKbAwV3cO+izlH9xShbOVgHjqRxSqovduSnDv1c7kOugKhM6BkhPiy+6LTCnXhxCnBw3jVVTAnzQ93mySMeS8GF5pmo+hb/3A="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
