travis:
  secure:
    BINSTAR_TOKEN: SfWhEGXyTe1uw+Whv+F0coHxmHdVCKX+rD+FqwYtVs6Y45A4Kr1jXguBAvz3TmtTBFFHqxpulCbpnWXAbvSh90Xzr5oJOMLIcwILe9ClZTlBnXfEcFPkjcwnQPRoo9VC+x58xAwA2G0FxKQh9eXdRJxiRVveOzFBBRSNsuTzCobzSKXKFYW/j//FBht/TxVovNn8ND0CHdC0JsWiszmNqai4cYIHpMlG4Pvzk+ouOCnIZYIIJXl4/fZSioHsUXeeF89fw7pNYt0NBjh5Yki31vMRFonicqlhKUYm+ENb26B5YOO/HHOASFy9ZlESVS0ZrwVYBkp5RuVLMrQj+uu5LKNmxXe7mS0vzxS5/tPaWIxmnB5KXodvQO0A5XUV6XlHFEvEFeYRdjx0aUvWPBsdtN6hrE268MIc7jkxBnkPcW1ERbPRRqPaVww2xU+vJpEzLkuP0h+G4H8dEQKKT2nVLG6G6pEIYisN/xK5bKni7GWq16byG4JKs5y2AAYPluASC9rHJivvjAuyLUKzzMNDgjOTLsrArfkF3dd/C1JGMMbBFTxzV7VXbBUN1x6t2B7EO/hgscony67gXmQhpkhiFquAfUky1euyAVkCg9ixKd4YngYqNOOmpcauUn+xPpDSaSM8n4E8kK7SIo0qveCy8cnWCXFGJIxLoCD/5xJnr2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
