travis:
  secure:
    BINSTAR_TOKEN: HgeExTsRD5YIIi/coz2cFi0RyScVTa1H+cRerJ1jSQlMNwqHUIUmTUgg6Vo1/tb24AEPmykW8t0okgkmxroXrr239XZc3KLoZRKSMU3zYyuZbICJ1Pcc1Vj5WavujLvvS3je/JX47We6c6etg7iVfzWjkggl3DnD8GIPaS9J5PSmf/d09FuBNYmbO4teq3c/15+LMNMcGRNTaXU6XR1H3irv9v+IF+o+p3cPNGjLjKal1A8PMVLPYb8W93SKU4Qbg5SpNwfNTMAlq7+oZNY2SfynVTVT7+zcFjpGh/UTBUpjyswYAad+iJN5T2a1UBqdJTYNWDBc9erlIT5zdPLTMFxMz6v5e0uGvIF9dFy8QYIIrFpEeRuKGVW7pq/xf8qle69QJ9D/tVZiQn5VSx+gmJ6C4j6pFdV72vKDlcsuTxv+9GNUGB/AOzi81JlXVrZsxSwLwUjnuKtPRkOYriqHb8EJE8ivAPDolDVK60fK1u/pcqun+jDbatfDQIwmvB6eJ1TR/NhDhdoRj/18A37/x/vDez9pC/9ykjEXmP1hRq3wpLO1Je+oDCkTX9f6vHqjlgup+wYTcsZKbAwV3cO+izlH9xShbOVgHjqRxSqovduSnDv1c7kOugKhM6BkhPiy+6LTCnXhxCnBw3jVVTAnzQ93mySMeS8GF5pmo+hb/3A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
